export type Channel = 'website' | 'tiktok' | 'shopee' | 'instagram';
export type Message = {id:string;role:'customer'|'ai'|'human'|'system';text:string;productId?:string;time:string};
export type Conversation = {id:string;channel:Channel;name:string;handle:string;initials:string;color:string;preview:string;time:string;unread:number;intent:string;messages:Message[]};
export type Product = {id:string;name:string;category:string;description:string;price:number;color:string;position:string};
export const products:Product[]=[
{id:'daily',name:'Daily Nutrition',category:'EVERYDAY ESSENTIALS',description:'Pilihan sederhana untuk rutinitas wellness harian.',price:189000,color:'#e9edde',position:'65% 60%'},
{id:'wellness',name:'Wellness Pack',category:'A LITTLE MORE BALANCE',description:'Satu paket untuk melengkapi momen merawat diri.',price:329000,color:'#eee8dc',position:'90% 45%'},
{id:'active',name:'Active',category:'MOVE WITH YOUR DAY',description:'Teman untuk keseharian yang aktif dan dinamis.',price:219000,color:'#e4e9e5',position:'75% 80%'},
{id:'immunity',name:'Immunity',category:'YOUR DAILY CARE',description:'Pilihan dalam koleksi perawatan diri harian.',price:249000,color:'#efe6d6',position:'68% 45%'}];
export const price=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const msg=(role:Message['role'],text:string,id:string,productId?:string):Message=>({id,role,text,productId,time:'09:41'});
const seeds:Record<Channel,Message[]>={
website:[msg('ai','Halo! Selamat datang di Vitalife 👋 Ada yang bisa saya bantu hari ini?','w1'),msg('customer','Saya mau cari produk untuk menjaga daya tahan tubuh.','w2'),msg('ai','Tentu, saya bisa bantu. Apakah untuk penggunaan sehari-hari atau kebutuhan tertentu?','w3')],
tiktok:[msg('customer','Kak produk ini masih ready?','t1'),msg('ai','Halo Kak Nadia! Saya bantu cek stok pada katalog demo terlebih dahulu ya.','t2'),msg('system','Pengecekan stok demo selesai','t3'),msg('ai','Di simulasi ini, produknya tersedia kak. Saya juga bisa membantu menjelaskan informasi dan cara penggunaannya.','t4'),msg('customer','Boleh kak, manfaatnya apa?','t5'),msg('ai','Tentu! Ini contoh Wellness Pack dalam katalog demo. Informasi manfaat resmi belum tersedia; saya bisa bantu hubungkan ke tim Vitalife untuk konfirmasi.','t6')],
shopee:[msg('customer','Halo kak, ini cocok untuk konsumsi harian?','s1'),msg('ai','Halo Kak! Saya bantu cek informasi produknya ya.','s2'),msg('ai','Dalam katalog demo, Wellness Pack digambarkan sebagai pilihan untuk rutinitas wellness harian. Kesesuaian konsumsi perlu dikonfirmasi berdasarkan label produk resmi.','s3'),msg('customer','Cara pakainya gimana?','s4'),msg('ai','Saya bisa bantu carikan petunjuknya. Dosis dan cara penggunaan resmi belum tersedia di demo ini. Mau saya hubungkan ke tim Vitalife?','s5')],
instagram:[msg('customer','Hai kak, aku lihat produk Vitalife dari Instagram. Bisa rekomendasi produk nggak?','i1'),msg('ai','Hai Kak! Tentu bisa 😊 Boleh tahu produk yang Kakak cari untuk kebutuhan apa?','i2'),msg('customer','Untuk jaga kondisi tubuh sehari-hari.','i3'),msg('ai','Baik kak. Berikut contoh pilihan dari katalog demo untuk kita eksplorasi bersama. Ini bukan rekomendasi medis atau informasi produk resmi.','i4','daily')]
};
const names:Record<Channel,string[]>= {website:['Guest'],tiktok:['Nadia','Raisa','Andi','Sarah','Dina'],shopee:['Putri','Dewi','Budi','Rani','Kevin'],instagram:['Nadia','Putri','Andrew','Dian','Melissa']};
const previews=['Kak ini ready?','Bisa COD nggak kak?','Produknya aman digunakan setiap hari?','Pesanan saya sudah dikirim belum?','Ada rekomendasi produk?'];
const colors=['#eddace','#e4e5f5','#dce8df','#f3e6d2','#eadfed'];
export const conversations:Conversation[]=Object.entries(names).flatMap(([channel,list])=>list.map((name,i)=>({id:`${channel}-${i}`,channel:channel as Channel,name,handle:channel==='instagram'?['@nadiaa','@putrifit','@andrew','@dianwellness','@melissa'][i]:`@${name.toLowerCase()}${i?'_'+(21+i):'.p'}`,initials:name.slice(0,1),color:colors[i],preview:channel==='instagram'&&i===0?'Bisa rekomendasi produk nggak?':previews[i],time:['09:41','09:35','09:22','Kemarin','Kemarin'][i],unread:i===0?2:i===1?1:0,intent:['Informasi produk','Pembayaran','Penggunaan produk','Tracking pesanan','Rekomendasi produk'][i],messages:i===0?seeds[channel as Channel]:[msg('customer',previews[i],`${channel}-${i}-1`),msg('ai',`Halo Kak ${name}! Saya siap membantu. ${i===1?'Di demo ini, opsi COD disimulasikan tersedia untuk wilayah tertentu. Ketersediaan sebenarnya mengikuti pilihan di marketplace.':i===2?'Keamanan dan cara konsumsi perlu mengikuti label resmi. Tim Vitalife bisa membantu mengonfirmasi informasinya.':i===3?'Boleh informasikan nomor pesanan demo, misalnya VL-DEMO-1042?':'Boleh tahu kebutuhan yang Kakak cari? Saya bisa menampilkan contoh pilihan dari katalog demo.'}`,`${channel}-${i}-2`)]})));
export const channelInfo:Record<Channel,{name:string;title:string;description:string;account:string;chips:string[]}>= {
website:{name:'Website Vitalife',title:'Website Vitalife',description:'Belanja dan konsultasi dalam satu pengalaman.',account:'Vitalife Assistant',chips:['Untuk sehari-hari','Lihat rekomendasi','Hubungi CS']},
tiktok:{name:'TikTok Shop',title:'TikTok Shop Inbox',description:'Dari ketertarikan di konten, jadi percakapan yang berarti.',account:'Vitalife Official',chips:['Cek stok','Lihat Produk','Cara Penggunaan','Tanya Produk Lain']},
shopee:{name:'Shopee Chat',title:'Shopee Chat',description:'Bantu customer menemukan jawaban sebelum berbelanja.',account:'Vitalife Official Store',chips:['Cara Penggunaan','Informasi Produk','Tracking pesanan','Tanya CS']},
instagram:{name:'Instagram DM',title:'Instagram Direct',description:'Percakapan personal untuk menemukan pilihan yang tepat.',account:'vitalife.wellness',chips:['Lihat rekomendasi','Tanya Produk Lain','Hubungi CS']}
};
