export function responseFor(text:string,handedOver:boolean){
const t=text.toLowerCase();
if(handedOver)return {text:'Halo, saya Maya dari tim Vitalife (simulasi). Pesan Kakak sudah saya terima. Boleh ceritakan detail kebutuhan Kakak?',status:'Human Agent sedang mengetik...',human:true};
if(/\bcs\b|customer service|manusia|human|agen|bicara|komplain/.test(t))return {text:'Tentu. Saya akan meneruskan percakapan ini ke tim Vitalife. Ringkasan percakapan sudah disertakan, jadi Kakak tidak perlu mengulang dari awal.',status:'Menyiapkan ringkasan percakapan...',handover:true};
if(/stok|stock|ready|tersedia/.test(t))return {text:'Stok demo berhasil dicek: Wellness Pack tersedia, 24 unit. Ini stok simulasi, bukan stok Vitalife sebenarnya. Mau lihat detail produknya?',status:'Checking product availability…',productId:'wellness'};
if(/kirim|pesanan|order|tracking|resi|vl-/.test(t))return /vl-|\d{4}/.test(t)?{text:'Pesanan contoh VL-DEMO-1042 sedang dalam perjalanan. Update demo: paket meninggalkan hub Jakarta, estimasi tiba 1–2 hari. Ini simulasi tracking, tanpa koneksi ke kurir.',status:'Checking demo order status…'}:{text:'Tentu, Kak. Ketik nomor pesanan contoh VL-DEMO-1042 untuk mencoba simulasi tracking.',status:'Mencari informasi pesanan…'};
if(/cara|pakai|konsumsi|dosis|kandungan|aman|manfaat|hamil|obat|sakit|alergi/.test(t))return {text:'Petunjuk penggunaan, kandungan, dan manfaat resmi belum dimasukkan ke demo ini. Saya tidak akan menebak dosis atau keamanan produk. Saya bisa menghubungkan Kakak ke tim Vitalife untuk konfirmasi informasi produk.',status:'Searching product information…'};
if(/cod|bayar|ongkir/.test(t))return {text:'Untuk simulasi ini, tersedia opsi pembayaran marketplace dan COD di wilayah tertentu. Biaya kirim serta ketersediaan sebenarnya mengikuti informasi resmi pada marketplace.',status:'Memeriksa opsi layanan demo…'};
if(/rekomendasi|sehari|harian|daya tahan|imun/.test(t))return {text:'Untuk kebutuhan harian, kita bisa mulai dengan Daily Nutrition dalam katalog demo. Ini contoh pilihan untuk mendemonstrasikan rekomendasi produk, bukan klaim manfaat atau saran medis.',status:'Searching product information…',productId:'daily'};
if(/produk|harga|detail|wellness/.test(t))return {text:'Berikut contoh Vitalife Wellness Pack dengan harga demo Rp329.000. Semua nama, harga, dan kemasan di katalog ini fiktif untuk presentasi. Mau lihat detail atau bertanya ke CS?',status:'Searching product information…',productId:'wellness'};
if(/terima kasih|makasih/.test(t))return {text:'Sama-sama, Kak! Senang bisa membantu 😊 Ada hal lain yang ingin ditanyakan?',status:'Menyiapkan jawaban…'};
return {text:'Baik, Kak. Saya bisa membantu melihat produk, cek stok demo, tracking pesanan, atau menghubungkan ke CS. Kebutuhan mana yang ingin Kakak bahas?',status:'Memahami kebutuhan customer…'};
}
