'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,CheckCheck,Leaf,Send,UserRound,Headphones,LoaderCircle,X,ShieldCheck,ArrowRight,MessageCircle} from 'lucide-react';
import {type Channel,type Conversation,type Message,type Product,products,channelInfo} from '@/lib/demo/data';
import {type ChatState} from '@/lib/demo/use-demo';
import {getWidgetUrl} from '@/lib/demo/widget-config';
import {ProductCard} from './product-card';
export function HumanHandoverBadge({human}:{human:boolean}){return <span className={`agent-badge ${human?'human':''}`}>{human?<Headphones size={12}/>:<Leaf size={12}/>} {human?'Human Agent':'AI Agent'}</span>}
export function ChatHeader({conversation,state,widget,onBack,onClose}:{conversation:Conversation;state:ChatState;widget?:boolean;onBack?:()=>void;onClose?:()=>void}){return <header className="chat-header">{onBack&&<button className="icon-button mobile-back" aria-label="Kembali ke daftar percakapan" onClick={onBack}><ArrowLeft size={20}/></button>}<span className={`avatar ${widget?'assistant-avatar':''}`} style={widget?{}:{background:conversation.color}}>{widget?<Leaf size={22}/>:conversation.initials}</span><div className="chat-person"><strong>{widget?'Vitalife Assistant':conversation.name}</strong><small>{widget?'Powered by SapaGo AI':conversation.handle+' · Customer'}</small></div><HumanHandoverBadge human={state.handover}/>{onClose&&<button className="icon-button" aria-label="Tutup chat" onClick={onClose}><X size={18}/></button>}</header>}
export function ChatBubble({message,onProduct}:{message:Message;onProduct:(p:Product)=>void}){if(message.role==='system')return <div className="system-message"><ShieldCheck size={13}/>{message.text}</div>;const agent=message.role!=='customer';const product=products.find(p=>p.id===message.productId);return <div className={`message ${agent?'agent-message':'customer-message'}`}>{agent&&<span className={`message-avatar ${message.role==='human'?'human':''}`}>{message.role==='human'?<UserRound size={14}/>:<Leaf size={14}/>}</span>}<div className="bubble-stack">{agent&&<span className="message-name">{message.role==='human'?'Maya · Human Agent':'Vitalife Assistant'}{message.role==='ai'&&<span>AI</span>}</span>}<div className="chat-bubble">{message.text}{product&&<ProductCard product={product} compact onOpen={onProduct}/>}</div><span className="message-time">{message.time}{!agent&&<CheckCheck size={13}/>}</span></div></div>}
export function QuickReply({labels,onSend,disabled}:{labels:string[];onSend:(s:string)=>void;disabled:boolean}){return <div className="quick-replies">{labels.map(label=><button key={label} disabled={disabled} onClick={()=>onSend(label)}>{label}<ArrowRight size={11}/></button>)}</div>}
export function ChatInput({onSend,disabled,human}:{onSend:(s:string)=>boolean;disabled:boolean;human:boolean}){const [value,setValue]=useState('');function submit(e:FormEvent){e.preventDefault();if(onSend(value))setValue('')}return <form className="chat-input-form" onSubmit={submit}><div className="chat-input-box"><input aria-label="Pesan customer" value={value} onChange={e=>setValue(e.target.value)} placeholder={human?'Tulis pesan untuk Maya…':'Tulis pesan sebagai customer…'} maxLength={2000}/><button type="submit" aria-label="Kirim pesan" disabled={disabled||!value.trim()}><Send size={17}/></button></div><div className="input-footnote"><span><ShieldCheck size={11}/> {human?'Ditangani Maya · Simulasi':'Percakapan demo · Respons tersimulasi'}</span><span>Powered by <b>SapaGo AI</b></span></div></form>}
export function ChatWindow({conversation,state,send,onProduct,widget=false,onBack,onClose}:{conversation:Conversation;state:ChatState;send:(id:string,s:string)=>boolean;onProduct:(p:Product)=>void;widget?:boolean;onBack?:()=>void;onClose?:()=>void}){const viewport=useRef<HTMLDivElement>(null);useEffect(()=>{const el=viewport.current;if(el)el.scrollTop=el.scrollHeight},[state.messages,state.typing,conversation.id]);return <section className={`chat-window ${widget?'widget-chat':''}`}><ChatHeader conversation={conversation} state={state} widget={widget} onBack={onBack} onClose={onClose}/>{conversation.channel==='shopee'&&<div className="product-context"><span>Customer menanyakan produk ini</span><ProductCard product={products[1]} compact onOpen={onProduct}/></div>}<div className="chat-messages" ref={viewport} role="log" aria-label={`Percakapan ${conversation.name}`} aria-live="polite"><div className="day-divider"><span/>Hari ini · Demo<span/></div>{state.messages.map(message=><ChatBubble message={message} key={message.id} onProduct={onProduct}/>)}{state.typing&&<div className="typing-state" role="status"><div className="typing-dots"><i/><i/><i/></div><span>{state.typing}</span></div>}</div>{state.handover&&<div className="handover-status"><Headphones size={14}/> Maya terhubung · Human Agent <span>Simulasi</span></div>}<QuickReply labels={state.handover?['Saya ingin tanya produk','Terima kasih']:channelInfo[conversation.channel].chips} onSend={s=>send(conversation.id,s)} disabled={!!state.typing}/><ChatInput key={conversation.id} onSend={s=>send(conversation.id,s)} disabled={!!state.typing} human={state.handover}/></section>}
/** Reusable replacement boundary: configured iframe or full simulated experience. */
export function SapaGoWidget({channel,children}:{channel:Channel;children:React.ReactNode}){const url=getWidgetUrl(channel);const [fallback,setFallback]=useState(false);if(url&&!fallback)return <section className="embed-container"><iframe src={url} title={`SapaGo AI – ${channelInfo[channel].name}`} sandbox="allow-scripts allow-same-origin allow-forms allow-popups" allow="clipboard-write" referrerPolicy="strict-origin-when-cross-origin"/><button className="embed-fallback" onClick={()=>setFallback(true)}>Widget tidak tampil? Gunakan simulasi</button></section>;return <>{children}</>}
export function WebsiteChat({open,setOpen,conversation,state,send,onProduct}:{open:boolean;setOpen:(v:boolean)=>void;conversation:Conversation;state:ChatState;send:(id:string,s:string)=>boolean;onProduct:(p:Product)=>void}){return <div className="website-chat-container">{open?<div className="floating-widget"><SapaGoWidget channel="website"><ChatWindow conversation={conversation} state={state} send={send} onProduct={onProduct} widget onClose={()=>setOpen(false)}/></SapaGoWidget>{getWidgetUrl('website')&&<button className="embed-close icon-button" aria-label="Tutup chat" onClick={()=>setOpen(false)}><X size={18}/></button>}</div>:<div className="chat-invite"><span><b>Ada yang bisa kami bantu?</b><small>Temukan pilihan wellness bersama kami.</small></span><button aria-label="Tutup sapaan" onClick={e=>e.currentTarget.parentElement?.classList.add('dismissed')}><X size={13}/></button></div>}<button className={`chat-launcher ${open?'is-open':''}`} onClick={()=>setOpen(!open)} aria-expanded={open}>{open?<X size={19}/>:<MessageCircle size={21}/>}<span>{open?'Tutup percakapan':'Chat dengan Vitalife'}</span>{!open&&<span className="launcher-dot"/>}</button></div>}
