'use client';
import {useState} from 'react';
import {Search,ChevronDown,Leaf,ShoppingBag,Music2,Camera,MessageSquare,Globe,ShieldCheck,UserRound,Headphones,ArrowUpRight} from 'lucide-react';
import {type Channel,type Product,type Conversation,conversations,channelInfo,products} from '@/lib/demo/data';
import {type ChatState} from '@/lib/demo/use-demo';
import {ChatWindow,SapaGoWidget,HumanHandoverBadge} from './chat';
import {ProductCard} from './product-card';
export const channelIcons={website:Globe,tiktok:Music2,shopee:ShoppingBag,instagram:Camera};
export function ConversationItem({conversation,state,selected,onClick}:{conversation:Conversation;state:ChatState;selected:boolean;onClick:()=>void}){const last=state.messages.at(-1);return <button className={`conversation-item ${selected?'selected':''}`} onClick={onClick} aria-pressed={selected}><span className="avatar" style={{background:conversation.color}}>{conversation.initials}</span><div className="conversation-summary"><div><strong>{conversation.channel==='instagram'?conversation.handle:conversation.name}</strong><small>{conversation.time}</small></div><p>{state.typing?'Asisten sedang mengetik…':last?.text||conversation.preview}</p><span className="conversation-tag">{state.handover?'Human Agent':conversation.intent}</span></div>{state.unread>0&&<span className="unread-count">{state.unread}</span>}</button>}
export function ConversationList({channel,selected,onSelect,states}:{channel:Channel;selected:string;onSelect:(id:string)=>void;states:Record<string,ChatState>}){const [query,setQuery]=useState('');const list=conversations.filter(c=>c.channel===channel&&`${c.name} ${c.handle}`.toLowerCase().includes(query.toLowerCase()));return <aside className="conversation-list"><div className="list-heading"><h3>Percakapan <span>5</span></h3><span className="list-filter">Semua pesan</span></div><label className="conversation-search"><Search size={15}/><input aria-label="Cari percakapan" placeholder="Cari customer…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="list-section-label">TERBARU</div><div className="conversation-items">{list.map(c=><ConversationItem key={c.id} conversation={c} state={states[c.id]} selected={selected===c.id} onClick={()=>onSelect(c.id)}/>)}{list.length===0&&<p className="empty-list">Tidak ada customer yang cocok.</p>}</div><div className="list-footer"><ShieldCheck size={14}/><span>Asisten aktif di channel ini<small>Powered by SapaGo AI</small></span></div></aside>}
export function Inbox({channel,states,send,onProduct,markRead}:{channel:Exclude<Channel,'website'>;states:Record<string,ChatState>;send:(id:string,s:string)=>boolean;onProduct:(p:Product,conversationId?:string)=>void;markRead:(id:string)=>void}){const [selected,setSelected]=useState(`${channel}-0`);const [mobileChat,setMobileChat]=useState(false);const c=conversations.find(c=>c.id===selected)!;const info=channelInfo[channel];const Icon=channelIcons[channel];return <section className={`inbox ${channel} ${mobileChat?'mobile-chat-open':''}`}><header className="inbox-topbar"><span className="channel-icon"><Icon size={21}/></span><div><h2>{info.title}</h2><span>{info.account}</span></div><div className="inbox-connected"><span className="status-dot"/>Simulasi terhubung</div><span className="inbox-demo-badge">DEMO</span></header><div className="inbox-layout"><ConversationList channel={channel} selected={selected} states={states} onSelect={id=>{setSelected(id);setMobileChat(true);markRead(id)}}/><div className="inbox-chat"><SapaGoWidget channel={channel}><ChatWindow conversation={c} state={states[selected]} send={send} onProduct={p=>onProduct(p,selected)} onBack={()=>setMobileChat(false)}/></SapaGoWidget></div><aside className="customer-panel"><div className="customer-panel-title"><UserRound size={14}/> Detail customer</div><span className="avatar profile-avatar" style={{background:c.color}}>{c.initials}</span><h3>{c.name}</h3><p>{c.handle}</p><span className="channel-profile"><Icon size={12}/>{info.name}</span><div className="profile-divider"/><label>DITANGANI OLEH</label><div className="handled-by"><span className="message-avatar"><Leaf size={14}/></span><div><strong>{states[selected].handover?'Maya':'Vitalife Assistant'}</strong><HumanHandoverBadge human={states[selected].handover}/></div></div><label>KEBUTUHAN CUSTOMER</label><div className="intent-chip">{c.intent}</div><label>PRODUK TERKAIT</label><ProductCard product={channel==='instagram'?products[0]:products[1]} compact onOpen={p=>onProduct(p,selected)}/><div className="context-note"><ShieldCheck size={16}/><p>Konteks percakapan ikut diteruskan saat beralih ke tim CS.</p></div><button className="handover-button" disabled={states[selected].handover||!!states[selected].typing} onClick={()=>send(selected,'Saya mau bicara dengan CS.')}><Headphones size={15}/>{states[selected].handover?'Ditangani Human Agent':'Simulasikan handover'}<ArrowUpRight size={14}/></button></aside></div></section>}
