'use client';
import {useState,useEffect} from 'react';
import {MessageCircle,RotateCcw,ArrowRight,ShoppingBag,Minus,Plus,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WebsiteStorefront} from '@/components/demo/storefront';
import {SapagoWebsiteLiveChat,focusSapagoLiveChat} from '@/components/demo/sapago-livechat';
import {Inbox,channelIcons} from '@/components/demo/inbox';
import {ProductCard} from '@/components/demo/product-card';
import {useDemo} from '@/lib/demo/use-demo';
import {type Channel,type Product,channelInfo,products,price} from '@/lib/demo/data';
const channels:Channel[]=['website','tiktok','shopee','instagram'];
function ChannelTabs(){return <TabsList className="channel-tabs">{channels.map(id=>{const Icon=channelIcons[id];return <TabsTrigger key={id} value={id}><Icon/>{channelInfo[id].name}<span className="tab-dot"/></TabsTrigger>})}</TabsList>}
export default function AppLayout(){const [tab,setTab]=useState<Channel>('website');const [product,setProduct]=useState<Product|null>(null);const [productConversation,setProductConversation]=useState('website-0');const openProduct=(p:Product,id='website-0')=>{setProductConversation(id);setProduct(p);};const [info,setInfo]=useState<string|null>(null);const [cart,setCart]=useState<Record<string,number>>({});const [notice,setNotice]=useState('');const {states,send,reset,markRead}=useDemo();const count=Object.values(cart).reduce((a,b)=>a+b,0);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer)},[notice]);
useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(v:unknown)=>Promise<unknown>};const context=(document as Document & {modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const nextPaint=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));try{void Promise.resolve(context.registerTool({name:'navigate_demo_channel',description:'Switch the visible Vitalife demo to a website or marketplace channel.',inputSchema:{type:'object',properties:{channel:{type:'string',enum:channels}},required:['channel'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{const c=(input as {channel?:Channel})?.channel;if(!c||!channels.includes(c))throw new Error('Invalid channel');setTab(c);await nextPaint();return {channel:c,simulation:true}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
const openWebsiteChat=()=>{setInfo(null);setProduct(null);const ready=focusSapagoLiveChat();setNotice(ready?'Widget SapaGo siap di kanan bawah.':'Widget SapaGo sedang dimuat. Coba lagi sesaat lagi.');};
const startProductChat=()=>{const p=product;setProduct(null);setInfo(null);if(tab==='website'){openWebsiteChat()}else{send(productConversation,p?`Saya ingin tahu produk ${p.name}`:'Saya mau bicara dengan CS.');setNotice('Pesan dikirim ke percakapan utama channel ini.')}};
return <main className="app-shell"><SapagoWebsiteLiveChat active={tab==='website'}/><header className="app-header"><div className="brand"><span className="sapago-mark"><MessageCircle size={21}/></span><strong>SapaGo<span>AI</span></strong><span className="brand-divider">×</span><span className="vitalife-brand">vitalife<span>®</span></span></div><div className="header-right"><button className="reset-button" aria-label="Reset demo" onClick={()=>{reset();setCart({});setNotice('Demo direset. Semua percakapan kembali ke awal.')}}><RotateCcw size={13}/><span>Reset demo</span></button><div className="demo-label"><span/> Enterprise Demo</div></div></header><section className="workspace-intro"><div><div className="eyebrow">CONNECTED EXPERIENCES</div><h1>Satu asisten. Setiap percakapan.</h1><p>Hadir untuk customer Vitalife, di mana pun mereka berada.</p></div><div className="agent-status"><span className="status-dot"/><div><strong>Vitalife Assistant</strong><small>SapaGo terhubung · 4 channel</small></div></div></section><Tabs value={tab} onValueChange={v=>setTab(v as Channel)}><div className="channel-nav"><ChannelTabs/><span className="demo-mode">DEMO WORKSPACE</span></div><TabsContent value="website" forceMount hidden={tab!=='website'}><WebsiteStorefront onProduct={openProduct} onInfo={setInfo} onChat={openWebsiteChat} onCart={()=>setInfo('cart')} cartCount={count}/></TabsContent>{channels.filter(c=>c!=='website').map(c=><TabsContent key={c} value={c} forceMount hidden={tab!==c}><Inbox channel={c as Exclude<Channel,'website'>} states={states} send={send} onProduct={openProduct} markRead={markRead}/></TabsContent>)}</Tabs><footer className="app-footer"><span>Vitalife Enterprise Prototype · Seluruh data adalah simulasi</span><span>Powered by <strong>SapaGo AI</strong></span></footer>
<Dialog open={!!product} onOpenChange={open=>!open&&setProduct(null)}><DialogContent className="product-dialog">{product&&<><div className="dialog-product-visual"><ProductCard product={product} compact onOpen={()=>{}}/></div><span className="eyebrow">KATALOG DEMO · BUKAN PRODUK RESMI</span><DialogTitle className="dialog-title">Vitalife {product.name}</DialogTitle><DialogDescription>{product.description} Nama, kemasan, harga, dan stok merupakan ilustrasi untuk presentasi.</DialogDescription><div className="dialog-price">{price(product.price)}<span>Harga demo</span></div><div className="product-facts"><div><span>Ketersediaan</span><b>24 unit · Simulasi</b></div><div><span>Cara penggunaan & kandungan</span><b>Menunggu data resmi</b></div></div><p className="product-caution">Tidak ada klaim manfaat, dosis, atau keamanan produk. Hubungi tim Vitalife untuk informasi resmi.</p><button className="primary-button" onClick={startProductChat}>Tanyakan ke asisten <MessageCircle size={16}/></button><button className="secondary-button" onClick={()=>{setCart(prev=>({...prev,[product.id]:(prev[product.id]||0)+1}));setNotice(`${product.name} ditambahkan ke keranjang demo.`);setProduct(null)}}>Tambah ke keranjang demo <Plus size={15}/></button></>}</DialogContent></Dialog>
<Dialog open={!!info} onOpenChange={open=>!open&&setInfo(null)}><DialogContent className="info-dialog"><DialogTitle>{info==='cart'?'Keranjang demo':'Tentang Vitalife'}</DialogTitle><DialogDescription>{info==='cart'?'Simulasi pilihan produk. Tidak ada pembayaran atau pesanan sungguhan.':'Pengalaman wellness yang lebih personal.'}</DialogDescription>{info==='cart'?<>{count===0?<div className="empty-cart"><ShoppingBag size={30}/><p>Keranjangmu masih kosong.</p><button className="primary-button" onClick={()=>{setInfo(null);document.getElementById('products')?.scrollIntoView({behavior:'smooth'})}}>Jelajahi produk <ArrowRight size={16}/></button></div>:<><div className="cart-items">{products.filter(p=>cart[p.id]>0).map(p=><div className="cart-item" key={p.id}><div><strong>{p.name}</strong><small>{price(p.price)} · Harga demo</small></div><div className="cart-quantity"><button aria-label={`Kurangi ${p.name}`} onClick={()=>setCart(prev=>({...prev,[p.id]:Math.max(0,prev[p.id]-1)}))}><Minus size={13}/></button><span>{cart[p.id]}</span><button aria-label={`Tambah ${p.name}`} onClick={()=>setCart(prev=>({...prev,[p.id]:prev[p.id]+1}))}><Plus size={13}/></button></div></div>)}</div><div className="cart-total"><span>Total demo</span><strong>{price(products.reduce((sum,p)=>sum+p.price*(cart[p.id]||0),0))}</strong></div><button className="primary-button" onClick={openWebsiteChat}>Konsultasikan pilihanmu <MessageCircle size={16}/></button></>}</>:<><p>Halaman ini memvisualisasikan pengalaman belanja dan customer service Vitalife bersama SapaGo AI. Koleksi produk dan seluruh informasi ditampilkan sebagai contoh fiktif untuk kebutuhan demo Enterprise.</p><button className="primary-button" onClick={openWebsiteChat}>Chat dengan Vitalife <MessageCircle size={16}/></button></>}</DialogContent></Dialog>{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}</main>}
